/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7kAEV2w9K6x
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function ConcertTicketForm() {
  return (
    <div className="max-w-md mx-auto my-8 p-6 bg-white shadow-md rounded-lg">
      <h1 className="text-lg font-semibold mb-4">Concert Tickets Available:</h1>
      <form>
        <div className="mb-4">
          <label className="block text-sm font-medium mb-1" htmlFor="front-row">
            Front Row
          </label>
          <Select>
            <SelectTrigger id="front-row">
              <SelectValue placeholder="0" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="1">1</SelectItem>
              <SelectItem value="2">2</SelectItem>
              <SelectItem value="3">3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="mb-4">
          <label className="block text-sm font-medium mb-1" htmlFor="middle-row">
            Middle Row
          </label>
          <Select>
            <SelectTrigger id="middle-row">
              <SelectValue placeholder="0" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="1">1</SelectItem>
              <SelectItem value="2">2</SelectItem>
              <SelectItem value="3">3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="mb-4">
          <label className="block text-sm font-medium mb-1" htmlFor="last-row">
            Last Row
          </label>
          <Select>
            <SelectTrigger id="last-row">
              <SelectValue placeholder="0" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="1">1</SelectItem>
              <SelectItem value="2">2</SelectItem>
              <SelectItem value="3">3</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="mb-4">
          <label className="block text-sm font-medium mb-1" htmlFor="total-cost">
            Total Cost:
          </label>
          <Input id="total-cost" placeholder="$0.00" readOnly />
        </div>
        <Button className="w-full">Mint</Button>
      </form>
    </div>
  )
}
